### PR TITLE
MaidSafe Developer site - Home, Core Developers and Careers page intergration

### PR DESCRIPTION
**Pull request by shankarsengalani**
Integration of Home, Core Developers and Careers page.

Following Images are yet to be added as not available
1. Career page banner image
2. Bread-cum arrow
3. Left Sidebar list arrow (up and down)
4. Footer Community Forums new Image

[Review on Reviewable](https://reviewable.io/reviews/maidsafe/dev.maidsafe.net/7)

### CODE REVIEW

**Comment by Viv-Rajkumar** [comment]
Cheers for the PR @shankar2105 :+1: 

Can you give a quick code review of this one @krishnaIndia while @NickLambert / @SWRobinson can check the site structure.

Being a new site, we prolly need to define a suitable naming convention for the html files. we've got names such as `google_analytics.html` but also `CoreDevelopers.html`. Best stick with lower case + separators.

**Comment by NickLambert** [comment]
Nice one @shankar2105.

I'll let @SWRobinson comment on the design, I remember Scott using some different images in his design (careers page).
I notice that underneath app dev support (in the footer) there is section(a) and section(b), not sure I remember these in the planned layout.
Router example should be Routing example and maybe we should just call this section 'Examples' and just use the name of each library as the page name (.i.e.) Routing Example becomes Routing?
Videos for core devs should probably just be called support videos.
Other than that looks pretty good as a first pass, great to have this site moving at last. Cheers Shankar.

**Comment by hitman401** [comment]
Good one @shankar2015 :)  There are lint errors, which you can get by running `grunt test`.
As @viv-rajkumar pointed out we can have file names to be consistent with lowercase and a separator. For eg `leftSidebar.html` should be left_side_bar.html

---

Reviewed 36 of 36 files at r1.
Review status: all files reviewed at latest revision, 5 unresolved discussions, all commit checks successful.

---

<sup>**[app/_includes/app_css.html, line 4 [r1]](https://reviewable.io:443/reviews/maidsafe/dev.maidsafe.net/7#-JwPuiFDAlqJx5rOc-Z7)** ([raw file](https://github.com/maidsafe/dev.maidsafe.net/blob/61e1e83eb48aada1ff344130affa71c56f2d53ac/app/_includes/app_css.html#L4)):</sup>
Can we remove the commented portion if it is not needed?

---

<sup>**[app/_includes/html/footer.html, line 16 [r1]](https://reviewable.io:443/reviews/maidsafe/dev.maidsafe.net/7#-JwPvYSkaVkuDPd5c5sO)** ([raw file](https://github.com/maidsafe/dev.maidsafe.net/blob/61e1e83eb48aada1ff344130affa71c56f2d53ac/app/_includes/html/footer.html#L16)):</sup>
This UI section breaks in scree size between 480 & 660 px

---

<sup>**[app/_includes/html/header.html, line 66 [r1]](https://reviewable.io:443/reviews/maidsafe/dev.maidsafe.net/7#-JwPvnbDLmoo8JcoYLUX)** ([raw file](https://github.com/maidsafe/dev.maidsafe.net/blob/61e1e83eb48aada1ff344130affa71c56f2d53ac/app/_includes/html/header.html#L66)):</sup>
Alignment

---

<sup>**[app/css/media.css, line 107 [r1]](https://reviewable.io:443/reviews/maidsafe/dev.maidsafe.net/7#-JwPxIUTy7S55_ybovvN)** ([raw file](https://github.com/maidsafe/dev.maidsafe.net/blob/61e1e83eb48aada1ff344130affa71c56f2d53ac/app/css/media.css#L107)):</sup>
We are missing screen range between 480 and 660 px and this is where the footer badges are getting mashed

---

<sup>**[app/js/app.js, line 65 [r1]](https://reviewable.io:443/reviews/maidsafe/dev.maidsafe.net/7#-JwPxn2D2qtEwJDZIV-F)** ([raw file](https://github.com/maidsafe/dev.maidsafe.net/blob/61e1e83eb48aada1ff344130affa71c56f2d53ac/app/js/app.js#L65)):</sup>
Use !== instead of !=.  Running `grunt test` will list the lint errors in js and css 

---

Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/maidsafe/dev.maidsafe.net/7)

**Comment by shankarsengalani** [comment]
<sup>**[app/_includes/app_css.html, line 4 [r1]](https://reviewable.io:443/reviews/maidsafe/dev.maidsafe.net/7#-JwPuiFDAlqJx5rOc-Z7)** ([raw file](https://github.com/maidsafe/dev.maidsafe.net/blob/61e1e83eb48aada1ff344130affa71c56f2d53ac/app/_includes/app_css.html#L4)):</sup>
Done.

---

Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/maidsafe/dev.maidsafe.net/7)

**Comment by shankarsengalani** [comment]
<sup>**[app/_includes/html/footer.html, line 0 [r1]](https://reviewable.io:443/reviews/maidsafe/dev.maidsafe.net/7#-JwPvYSkaVkuDPd5c5sO)** ([raw file](https://github.com/maidsafe/dev.maidsafe.net/blob/61e1e83eb48aada1ff344130affa71c56f2d53ac/app/_includes/html/footer.html#L0)):</sup>
Done.

---

Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/maidsafe/dev.maidsafe.net/7)

**Comment by shankarsengalani** [comment]
<sup>**[app/_includes/html/header.html, line 0 [r1]](https://reviewable.io:443/reviews/maidsafe/dev.maidsafe.net/7#-JwPvnbDLmoo8JcoYLUX)** ([raw file](https://github.com/maidsafe/dev.maidsafe.net/blob/61e1e83eb48aada1ff344130affa71c56f2d53ac/app/_includes/html/header.html#L0)):</sup>
Done.

---

Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/maidsafe/dev.maidsafe.net/7)

**Comment by shankarsengalani** [comment]
<sup>**[app/js/app.js, line 0 [r1]](https://reviewable.io:443/reviews/maidsafe/dev.maidsafe.net/7#-JwPxn2D2qtEwJDZIV-F)** ([raw file](https://github.com/maidsafe/dev.maidsafe.net/blob/61e1e83eb48aada1ff344130affa71c56f2d53ac/app/js/app.js#L0)):</sup>
Done.

---

Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/maidsafe/dev.maidsafe.net/7)

**Comment by shankarsengalani** [comment]
<sup>**[app/css/media.css, line 0 [r1]](https://reviewable.io:443/reviews/maidsafe/dev.maidsafe.net/7#-JwPxIUTy7S55_ybovvN)** ([raw file](https://github.com/maidsafe/dev.maidsafe.net/blob/61e1e83eb48aada1ff344130affa71c56f2d53ac/app/css/media.css#L0)):</sup>
Done.

---

Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/maidsafe/dev.maidsafe.net/7)

**Comment by SWRobinson** [comment]
Hi @shankar2105 , this looks like a really great start! :smile:  There are a few style issues with it though which I've outlined below:

---

The breakpoints as per the reference design were <480, <768, <1024.

---

It seems that the styling for the largest (>1024) screen size no longer works
style_large
.

---

Firefox renders the first banner text as Times New Roman.

---

The width of the main body area(nav, content, everything) is 960px at sizes between 1024px and 1920px.
content_width

 Below this it scales according to screen size.

---

The font sizes for the second banner should be the same as the top. I can't check them at the minute because the largest size isn't working but the sizes should be
heading: <480 - 30px/36px, <768 - 30px/36, >1024 - 49px/59px
body area: <480 - 14px/17px, <768 - 14px/17px, >1024 - 24px/27px

---

The Navigation bar which appears a little off at all sizes.

at 1800px: 
The menu options (app dev, core dev, etc) are not right-aligned with the container edge.
The text of each item is too small, they should be 18px but instead are 14px.

at 1024px:
The same issues exist, see image below.
nav_example

at 768px:
The menu icon is too close to the right edge and should match the padding of the main logo (40px).
The maidsafe logo should also be left-aligned with the edge of the screen when scaling with 40px keft padding.

at 480px: 
Padding on the left and right of the screen should change to 18px.
The maidsafe logo should change to the abreviated MaidSafe dev logo and should not scale at this point.
nav_mobile

**Comment by shankarsengalani** [comment]
CSS fixes pointed out by @SWRobinson has been fixed.

**Comment by SWRobinson** [comment]
@shankar2105 That's looking better, there are still a few problems and I'll point them out later when I've gone through it all. For now, there's an issue with the spacing of the footer links. 

When at ~1650px wide a gap between the links starts to appear:
large_gap

This is it at a very wide size:
xl_gap

and the same at the smallest size before it changes to two columns:
medium_overlap

There should be no gaps/overlaps happening with each of the items evenly spaced out. As we can see, on the smallest size there is space on either side for them to take up.

**Comment by shankarsengalani** [comment]
Hi @SWRobinson Footer spacing has been fixed.

**Comment by Viv-Rajkumar** [comment]
@shankar2105 Please do remove `Gemfile.lock` from this PR. It's what seems to be causing the travis CI failure for this PR. maybe needs added to the `.gitignore` list

**Comment by shankarsengalani** [comment]
@Viv-Rajkumar Gemfile.lock has been added to gitignorelist and now the build passed.

**Pull request merged**
